---

# Some default cluster settings
psql_version: 9.4
psql_cluster_name: "main"
psql_owner: "postgres"

# dictionary that represents configuration
# XXX subsections keys must be valid psql configuration keys.
psql_default_conf:
  files:
    data_directory: "/var/lib/postgresql/{{ psql_version }}/{{ psql_cluster_name }}"
    hba_file: "/etc/postgresql/{{ psql_version }}/{{ psql_cluster_name }}/pg_hba.conf"
    ident_file: "/etc/postgresql/{{ psql_version }}/{{ psql_cluster_name }}/pg_ident.conf"
    external_pid_file: "/var/run/postgresql/{{ psql_version }}/{{ psql_cluster_name }}.pid"
  conn_and_auth:
    listen_addresses: ["*"]
    port: 5432
    max_connections: 1000 # n.b. 1 connection == 400 bytes shared memory plus lock space
    superuser_reserved_connections: 10
    unix_socket_directories: ["/var/run/postgresql"]
    unix_socket_group: ""
    unix_socket_permissions: "0777"
    authentication_timeout: "1m"
    ssl: off
    ssl_ciphers: "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:AES128-SHA"
    ssl_cert_file: "/etc/ssl/cert/{{ certificate }}.pem"
    ssl_key_file: "/etc/ssl/private/{{ certificate }}.key"
    ssl_ca_file: ""
    ssl_crl_file: ""
    password_encryption: on
    tcp_keepalives_idle: 0
    tcp_keepalives_interval: 0
    tcp_keepalives_count: 0
  resources:
    shared_buffers: "64M"
    temp_buffers: "16M"
    work_mem: "2M"
    temp_file_limit :"-1"                  # limits per-session temp file space
    max_files_per_process: "2000"          # min 25
    shared_preload_libraries: ''           # (change requires restart)
    vacuum_cost_delay: 0                   # 0-100 milliseconds
    vacuum_cost_page_hit: 1                # 0-10000 credits
    vacuum_cost_page_miss: 10              # 0-10000 credits
    vacuum_cost_page_dirty: 20             # 0-10000 credits
    vacuum_cost_limit: 200                 # 1-10000 credits
    bgwriter_delay: "200ms"                # 10-10000ms between rounds
    bgwriter_lru_maxpages: 100             # 0-1000 max buffers written/round
    bgwriter_lru_multiplier: "2.0"         # 0-10.0 multipler on buffers scanned/round
    effective_io_concurrency: 1            # 1-1000; 0 disables prefetching
  wal:
  repl:
  query_tuning:
  error_reporting_and_logging:
  runtime_stats:
  autovacuum:
  client_defaults:
  lock_mgmt:
  compat:
  errors:
  extensions:
