# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e1f4098eb0edc3bbaaf3aacd254d01c4d2e7707f56d5e6d53c0cdc8df810fe494f0907d53cacce1cc361b07431b4275c2e4742267302b2dfbfda3ce1e5ef788

test:
  secret_key_base: b5a6c6db00a7e82343cca222d2c1fa6fb8cd7042717dc05eb356fac29b5e609023423bb8c7f5b8a53454b1fc96be20ae5b1cc8a12a5306c679e5bbcdc31c96d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
